application: marvel-college
version: 1
runtime: php55
api_version: 1

handlers:
- url: /
  script: index.html

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /index
  script: index.html

- url: /about.html
  script: about.html

- url: /admin
  script: admin.php

- url: /resetpassword
  script: reset.php

- url: /faculty
  script: faculty.php

- url: /finfo
  script: finfo.php

- url: /fgrade
  script: fgrade.php

- url: /coursecatalog
  script: coursecatalog.php

- url: /createcourse
  script: createcourse.php

- url: /test
  script: test.php

- url: /logout.php
  script: logout.php

- url: /login
  script: login.php

- url: /student
  script: student.php

- url: /transcript
  script: transcript.php

- url: /generate
  script: generate.php

- url: /adddrop
  script: adddrop.php

- url: /Vstudent
  script: Vstudent.php

- url: /.*
  script: 404.html